[build-system]
requires = [ "setuptools", "setuptools_scm" ]
build-backend = "setuptools.build_meta"

[project]
name = "ts_lasertracker"
description = "CSC to make the dome for the Rubin Observatory Simonyi Survey Telescope dome track the telescope."
license = { text = "GPL" }
classifiers = [ "Programming Language :: Python :: 3" ]
urls = { documentation = "https://ts-lasertracker.lsst.io", repository = "https://github.com/lsst-ts/ts_lasertracker" }
dynamic = [ "version" ]

[tool.setuptools.dynamic]
version = { attr = "setuptools_scm.get_version" }

[tool.setuptools.packages.find]
where = [ "python" ]

[project.scripts]
run_lasertracker = "lsst.ts.lasertracker:run_lasertracker"

[tool.setuptools_scm]

[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"
 
[project.optional-dependencies]
dev = ["documenteer[pipelines]"]
